[package]
categories = ["api-bindings", "wasm"]
description = "WasmEdge Runtime is a high-performance, extensible, and hardware optimized WebAssembly Virtual Machine for automotive, cloud, AI, and blockchain applications."
documentation = "https://wasmedge.github.io/wasmedge-rust-sdk/wasmedge_sdk/"
edition.workspace = true
exclude = ["examples/"]
license.workspace = true
name = "wasmedge-sdk"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.16.1"

[dependencies]
anyhow = "1.0"
cfg-if.workspace = true
num-derive = "0.3"
num-traits = "0.2"
thiserror.workspace = true
wasmedge-macro.workspace = true
wasmedge-sys = { path = "crates/wasmedge-sys", version = "0.20.0", default-features = false }
wasmedge-types.workspace = true

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/WasmEdge/wasmedge-rust-sdk"
rust-version = "1.85"

[workspace.dependencies]
async-wasi = { path = "crates/async-wasi", version = "0.2.0" }
bindgen = { version = "0.69", default-features = false }
bitflags = "2.0.2"
cfg-if = "1.0.0"
futures = "0.3"
getrandom = "0.2"
libc = "0.2.186"
log = "0.4"
parking_lot = "0.12.1"
slab = "0.4.12"
socket2 = "0.4.9"
thiserror = "1.0.30"
tokio = "1.43"
wasmedge-macro = { path = "crates/wasmedge-macro", version = "0.6" }
wasmedge-types = { path = "crates/wasmedge-types", version = "0.6" }
wat = "1.0"

[target.'cfg(target_os = "linux")'.dependencies]
async-wasi = { workspace = true, optional = true }

[features]
aot = ["wasmedge-sys/aot"]
async = ["wasmedge-sys/async", "dep:async-wasi"]
bundled = ["wasmedge-sys/bundled"]
default = ["async"]
ffi = ["wasmedge-sys/ffi"]
standalone = ["wasmedge-sys/standalone"]
static = ["wasmedge-sys/static"]
wasi_crypto = ["wasmedge-sys/wasi_crypto"]
wasi_nn = ["wasmedge-sys/wasi_nn"]
wasmedge_process = ["wasmedge-sys/wasmedge_process"]

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }

[[example]]
name = "run_wasm"
path = "examples/run_wasm.rs"

[package.metadata.docs.rs]
features = ["aot", "wasi_crypto", "wasi_nn", "wasmedge_process", "ffi"]
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[workspace]
members = [
    "crates/wasmedge-sys",
    "crates/wasmedge-types",
    "crates/wasmedge-macro",
    "crates/async-wasi",
]
exclude = ["test-wasm"]
resolver = "3"

[workspace.lints.rust]
unused_extern_crates = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"
trivial_numeric_casts = "warn"
unused_import_braces = "warn"

[workspace.lints.clippy]
uninlined_format_args = "warn"
clone_on_copy = "warn"
dbg_macro = "warn"

[profile.dev.package."*"]
debug = false
