[package]
build = "build.rs"
categories = ["api-bindings", "wasm"]
description = "WasmEdge Runtime is a high-performance, extensible, and hardware optimized WebAssembly Virtual Machine for automotive, cloud, AI, and blockchain applications."
documentation = "https://wasmedge.github.io/wasmedge-rust-sdk/wasmedge_sys/"
edition.workspace = true
exclude = ["tests/", "examples/"]
license.workspace = true
links = "wasmedge"
name = "wasmedge-sys"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.20.0"

[dependencies]
log.workspace = true
fiber-for-wasmedge = { version = "14.0.4", optional = true }
libc.workspace = true
scoped-tls = "1"
wasmedge-types.workspace = true
wat.workspace = true


[target.'cfg(target_os = "linux")'.dependencies]
async-wasi = { workspace = true, optional = true }
setjmp = "0.1"

[build-dependencies]
bindgen = { workspace = true, features = ["runtime"] }
reqwest = { version = "0.11", default-features = false, features = [
    "blocking",
    "rustls-tls",
] }
flate2 = "1"
tar = "0.4.46"
sha256 = "1"
phf = { version = "0.11", features = ["macros"] }


[dev-dependencies]
tokio = { workspace = true, features = ["full"] }


[package.metadata.docs.rs]
features = ["aot", "wasi_crypto", "wasi_nn", "wasmedge_process", "ffi"]
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[features]
aot = []
async = ["dep:fiber-for-wasmedge", "dep:async-wasi"]
bundled = ["standalone", "static"]
default = []
ffi = []
standalone = []
static = []
wasi_crypto = []
wasi_nn = []
wasmedge_process = []
