name: Release wasmedge-types crate

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on: workflow_dispatch

jobs:
  release_wasmedge_types:
    name: Release wasmedge-types crate
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
      - name: Checkout WasmEdge Rust SDK
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust v1.68
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.68

      - name: Dry run cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRIES_TYPES_TOKEN }}
        shell: bash
        run: |
          cargo publish --dry-run -p wasmedge-types

      - name: Publish
        if: github.ref == 'refs/heads/main'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRIES_TYPES_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          cargo publish -p wasmedge-types

      - name: Build API document
        run: |
          cargo doc -p wasmedge-types --no-deps --target-dir=./target

      - name: Deploy API document
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: target/doc
          force_orphan: true
